version: "3"
services:
  # Database
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
  # API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.web
    ports:
    - "3000:3000"
    environment:
    - MONGODB_URI=mongodb://mongo:27017
    depends_on:
    - mongo
  # Worker
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    environment:
     - LOG_LEVEL=debug
     - MONGODB_URI=mongodb://mongo:27017
     - ETH_NODE=wss://mainnet.eth.aragon.network/ws
    depends_on:
     - mongo

volumes:
  mongo-data:
